<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Macro for the inertia of a box -->
  <xacro:macro name="box_inertia" params="x y z mass">
    <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
      izz="${0.0833333 * mass * (x*x + y*y)}" />
  </xacro:macro>

  <!-- Macro for the inertial properties of a box -->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <xacro:box_inertia x="${x}" y="${y}" z="${z}" mass="${mass}" />
    </inertial>
  </xacro:macro>

  <!-- Macro for sphere joint with force sensor -->
  <xacro:macro name="sphere_joint" params = "robot_namespace joint_velocity_limit joint_effort_limit parent_link_holder *origin_from_parent">


    <joint name="${robot_namespace}/sphjoint1" type="continuous">
      <parent link="${parent_link_holder}"/>
      <child link="${robot_namespace}/sphlink_z"/>
      <axis xyz="0 0 1" />
      <insert_block name="origin_from_parent"/>
      <limit lower="${-pi/2}" upper="${pi/2}" velocity="${joint_velocity_limit}" effort="${joint_effort_limit}" />
    </joint>
    <link name="${robot_namespace}/sphlink_z">
      <inertial>
        <mass value="0.025" />
        <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
      </inertial>  
    </link>

    <joint name="${robot_namespace}/sphjoint0" type="revolute">
      <parent link="${robot_namespace}/sphlink_z"/>
      <child link="${robot_namespace}/sphlink_y"/>
      <axis xyz="0 1 0" />
      <limit lower="${-pi/4}" upper="${pi/4}" velocity="${joint_velocity_limit}" effort="${joint_effort_limit}" />
    </joint>
    <link name="${robot_namespace}/sphlink_y">
      <inertial>
        <mass value="0.025" />
        <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
      </inertial>
    </link>

    <joint name="${robot_namespace}/sphjoint2" type="revolute">
      <parent link="${robot_namespace}/sphlink_y"/>
      <child link="${robot_namespace}/sphlink_x"/>
      <axis xyz="1 0 0" />
      <limit lower="${-pi/4}" upper="${pi/4}" velocity="${joint_velocity_limit}" effort="${joint_effort_limit}" />
    </joint>
    <link name="${robot_namespace}/sphlink_x">
      <inertial>
        <mass value="0.025" />
        <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
      </inertial>  
    </link>

    <joint name="${robot_namespace}/sphjointfixed" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${robot_namespace}/sphlink_x"/>
        <child link="${robot_namespace}/base_link_inertia"/>
      <sensor name="${robot_namespace}/f_t" type="force_torque">
        <update_rate>100</update_rate>
      </sensor>
    </joint>
    <gazebo reference="${robot_namespace}/sphjoint0">
        <provideFeedback>true</provideFeedback>
    </gazebo>
    <gazebo>
      <plugin name="${robot_namespace}/ft_sensor_plugin" filename="libgazebo_ros_ft_sensor.so">
        <updateRate>100.0</updateRate>
        <topicName>${robot_namespace}/f_t</topicName>
        <jointName>${robot_namespace}/sphjoint0</jointName>
      </plugin>
    </gazebo>
  </xacro:macro>


  <!-- Main multirotor link -->
  <xacro:macro name="multirotor_base_macro"
    params="robot_namespace enable_base_link base_link  
            sphere_joint_name parent_link_holder offset_holder
            mass body_width body_height use_mesh_file mesh_file 
            joint_velocity_limit joint_effort_limit *inertia">
    <xacro:if value="${enable_base_link}">
      <link name="${base_link}"></link>
      <joint name="${robot_namespace}/base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="${base_link}" />
        <child link="${robot_namespace}/base_link_inertia" />
      </joint>
    </xacro:if>
    
    <xacro:sphere_joint
      robot_namespace = "${robot_namespace}"
      parent_link_holder = "${parent_link_holder}"
      joint_velocity_limit = "${joint_velocity_limit}"
      joint_effort_limit = "${joint_effort_limit}"
      >
      <origin xyz="0 0 ${offset_holder}" rpy="0 0 0"/>
    </xacro:sphere_joint>


    <link name="${robot_namespace}/base_link_inertia">
      <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <!-- <insert_block name="visual_origin"/> -->
        <xacro:insert_block name="inertia" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <xacro:if value="${use_mesh_file}">
            <mesh filename="${mesh_file}" scale="1 1 1" />
          </xacro:if>
          <xacro:unless value="${use_mesh_file}">
            <box size="${body_width} ${body_width} ${body_height}"/> <!-- [m] [m] [m] -->
          </xacro:unless>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${body_width} ${body_width} ${body_height}" /> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>

    <!-- attach multirotor_base_plugin to the base_link -->
    <gazebo>
      <plugin filename="librotors_gazebo_multirotor_base_plugin.so" name="multirotor_base_plugin">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <linkName>${robot_namespace}/base_link_inertia</linkName>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
  </xacro:macro>

  <!-- Rotor joint and link -->
  <xacro:macro name="vertical_rotor"
    params="robot_namespace suffix direction motor_constant moment_constant parent mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color use_own_mesh mesh *origin *inertia">
    <joint name="${robot_namespace}/rotor_${motor_number}_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <!-- TODO(ff): not currently set because it's not yet supported -->
      <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
      <parent link="${parent}" />
      <child link="${robot_namespace}/rotor_${motor_number}" />
    </joint>
    <link name="${robot_namespace}/rotor_${motor_number}">
      <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <!-- <cylinder length="0.005" radius="${radius_rotor}"/> --> <!-- [m] -->
          <xacro:if value="${use_own_mesh}">
            <mesh filename="${mesh}"
              scale="1 1 1" />
          </xacro:if>
          <xacro:unless value="${use_own_mesh}">
            <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae"
              scale="${radius_rotor} ${radius_rotor} ${radius_rotor}" /> <!-- The propeller meshes have a radius of 1m -->
            <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
          </xacro:unless>
        </geometry>
      </visual>
      <collision>
        <!-- <insert_block name="visual_origin"/> -->
        <geometry>
          <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo>
      <plugin name="${robot_namespace}_${suffix}_motor_model" filename="librotors_gazebo_motor_model.so">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <jointName>${robot_namespace}/rotor_${motor_number}_joint</jointName>
        <linkName>${robot_namespace}/rotor_${motor_number}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>${time_constant_up}</timeConstantUp>
        <timeConstantDown>${time_constant_down}</timeConstantDown>
        <maxRotVelocity>${max_rot_velocity}</maxRotVelocity>
        <motorConstant>${motor_constant}</motorConstant>
        <momentConstant>${moment_constant}</momentConstant>
        <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
        <motorNumber>${motor_number}</motorNumber>
        <rotorDragCoefficient>${rotor_drag_coefficient}</rotorDragCoefficient>
        <rollingMomentCoefficient>${rolling_moment_coefficient}</rollingMomentCoefficient>
        <motorSpeedPubTopic>motor_speed/${motor_number}</motorSpeedPubTopic>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
    <gazebo reference="${robot_namespace}/rotor_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>
</robot>
